# Generated by Django 3.1 on 2020-08-14 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetoNovels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usuario',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Usuarios'},
        ),
    ]
