# Generated by Django 3.1 on 2020-08-14 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetoNovels', '0002_auto_20200814_0021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
